version: '2.4'

services:
  backend:
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pgdb/postgres
    depends_on:
      pgdb:
        condition: service_healthy

  pgdb:
    image: postgres:12.3-alpine
    ports:
        - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
